version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - cd shoppy-backend
      - npm install -g pnpm
      - pnpm install
  build:
    commands:
      - cd shoppy-backend
      - pnpm prisma generate
      - pnpm build
artifacts:
  base-directory: shoppy-backend
  files:
    - "**/*"
