version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - cd shoppy-backend   # <--- thêm dòng này
      - npm install -g pnpm
      - pnpm install
  build:
    commands:
      - cd shoppy-backend   # <--- thêm dòng này, nếu cần
      - pnpm prisma generate
      - pnpm build
artifacts:
  files:
    - '**/*'
