
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Container, CssBaseline } from "@mui/material";
import Headers from "./header/header";
import Providers from "./providers";
import authenticated from "./auth/authenticated";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAuthenticated = await authenticated(); // kiểm tra cookie ở server
//Là cầu nối giữa server và client.
// Nhận trạng thái isAuthenticated từ server action.
// Truyền nó xuống client qua component <Providers>.
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers authenticated={isAuthenticated}>
            <CssBaseline/>
            <Headers />
            <Container>{children}</Container>  
        </Providers> 
      </body>
    </html>
  );
}
